id: P108706AF
initial_creation_type: ocr
source_metadata:
  volumes:
    1e8dfea9b87f4fc49fba5321971e2fad:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: སྒྲོལ་མ་དཀོན་མཆོག་གསུམ་ལ་བསྟོད་པ།
      total_pages: 1856
      volume_number: 14
